### PR TITLE
Improve functionality to manage multiple carets.

### PR DESCRIPTION
**Pull request by JairoMartinezA**
Hi @Alexey-T 

Could you review the changes made? It was modified the functionality base to accept multiples carets.

Greetings.

### CODE REVIEW

**Comment by Alexey-T** [comment]
Thanks 

- can you use ed.replace instead of Ed.delete / ed.insert?

- can you keep all carets after work? Set_caret has the action to change one caret and keep others

**Comment by Alexey-T** [comment]
Typo in readme? Or -> of

**Comment by JairoMartinezA** [comment]
OK let me work on that.

**Comment by JairoMartinezA** [comment]
Ready @Alexey-T,

You can validate the latest changes.

**Comment by CudaText-addons** [comment]
thanks! plugin was updated in AddonManager.

**Pull request merged**
